language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "pypy"
    - "pypy3"
install:
    - pip install tox
script: tox
before_install:
    - pip install codecov
after_success:
    - codecov
