language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"

before_install:
    - pip install codecov

install:
    - pip install -r development.txt

script: nosetests --rednose -v tests/unit --with-cover --cover-package=radish && ./tests/functional.sh

after_success:
    - codecov
